### ISSUE TITLE
Fjern esyfovarsel-FSS fra accessPolicy

### ISSUE THREAD

**Issue by torchr89** [navikt/narmesteleder#118]
esyfovarsel er migrert fra FSS til GCP. Derfor kan FSS-innslagene (men ikke GCP) her:

https://github.com/navikt/narmesteleder/blob/main/naiserator-dev.yaml#L91-L93 

og her:

https://github.com/navikt/narmesteleder/blob/main/naiserator-prod.yaml#L88-L90

fjernes fra inbound access policy.

**Comment by MikAoJk** [comment]
@torchr89 hadde du giddet å lage ein pr😊?

**Comment by MikAoJk** [comment]
Det stemmer nok, du må nok forke repoet

**Comment by torchr89** [comment]
@MikAoJk 
PR her:
https://github.com/navikt/narmesteleder/pull/121
